spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER} # Read from environment variable
    password: ${DB_PASSWORD} # Read from environment variable
    url: jdbc:postgresql://localhost:5432/user_management
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: false
        dialect: ${spring.jpa.database-platform}
logging:
  level:
    org.hibernate.sql: DEBUG
