db:
  name: user_management
  user: postgres
  password: dan1981
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${db.user}
    password: ${db.password}
    url: jdbc:postgresql://localhost:5432/${db.name}
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    database: postgresql


server:
  port: 4000
  servlet:
    context-path: /user-management
